#!/usr/bin/with-contenv bash
. /usr/local/bin/variables

if [ ! -f "$PLEX_AUTOSCAN_CONFIG" ]; then
    s6-svc -d .
    exit 0
fi

if [ -z "$PLEX_AUTOSCAN_URL" ] || [ -z "$PLEX_AUTOSCAN_API" ]; then
    s6-svc -d .
    exit 0
fi

if [ -z "${WATCHER_DIRS:-}" ]; then
    s6-svc -d .
    exit 0
fi

s6-svwait -u /var/run/s6-rc/servicedirs/svc-autoscan

until curl -fs -X GET "${PLEX_AUTOSCAN_API}?cmd=queue_count" >/dev/null 2>&1; do
    sleep 30
done


CURL_OPTS="-fsS -X POST -o /dev/null"

# replace all newlines with |, then split on |
IFS="|" read -r -a WDIRS <<< "${WATCHER_DIRS//$'\n'/|}"

WATCHER_DIRS=()
for dir in "${WDIRS[@]}"; do
    dir_trimmed="$(echo "$dir" | xargs)"  # remove whitespace
    [[ -n "$dir_trimmed" ]] && WATCHER_DIRS+=("$dir_trimmed")
done

if [ "${WATCHER_DIRS_BRACE_EXPANSION:-0}" -eq 1 ]; then
    # applying bash brace expansion for a list of vertical-bar-separated paths
    # 1. escape spaces using variable substitution
    # 2. apply brace expansion using 'eval printf'
    # 3. readarray from the result of #2 and append to existing one
    expdirs=()
    for WDIR in "${WATCHER_DIRS[@]}"; do
        readarray -t -O"${#expdirs[@]}" expdirs <<< "$(eval printf '"%s\n"' "${WDIR// /\\ }")"
    done
    WATCHER_DIRS=("${expdirs[@]}")
fi

exec /usr/local/bin/watcher \
    -dotfiles="${WATCHER_DOTFILES:-false}" \
    -interval="${WATCHER_INTERVAL:-60s}" \
    -pipe=true \
    "-cmd=xargs -0 -I {} curl $CURL_OPTS -d eventType=Watcher --data-urlencode pipe={} $PLEX_AUTOSCAN_URL" \
    "${WATCHER_DIRS[@]}"
