#!/usr/bin/with-contenv bash

if [[ "${PLEX_CACHER_ENABLED:-false}" != "true" ]]; then
    exit 0
fi

echo "*** installing Plex cacher Python dependencies"
python3 -m pip -q install -U \
    plexapi \
    psutil \
    websocket-client

exit 0
