#!/usr/bin/with-contenv bash

if [[ -d "/var/run/s6-rc/servicedirs/svc-plex" ]]; then
    # lsio/plex
    s6-svwait -U /var/run/s6-rc/servicedirs/svc-plex
else
    # plexinc/pms-docker
    s6-svwait -u /var/run/s6/services/plex
fi

if [[ -n "${CLEANUP_PTC_CRON:-}" ]]; then
    echo "*** scheduling job: cleanup phototranscoder"
    go-cron "$CLEANUP_PTC_CRON" /usr/local/bin/cleanup-ptc &
    sleep 2
fi

exec wait
