#!/usr/bin/with-contenv bash
. /usr/local/bin/variables

# checks
if [ -z "${PLEX_RAMDB_ROOT}" ]; then
	exit 0
fi
if [ ! -d "${PLEX_RAMDB_ROOT}" ]; then
	exit 0
fi
if ! findmnt "${PLEX_RAMDB_ROOT}" | grep -q tmpfs; then
	# ensuring provided PLEX_RAMDB_ROOT is tmpfs mount
    exit 0
fi


if [ ! -d "${PLEX_DB_ROOT}" ]; then
	exit 0
fi
if mountpoint -q "${PLEX_DB_ROOT}"; then
	exit 0
fi

printf "true" > /var/run/s6/container_environment/PLEX_RAMDB_ENABLED

echo "*** loading database on ram..."
/usr/local/bin/ramdb load
